version: '3.8'
services:
  mongodb:
    image: mongo 
    restart: always
  
  rabbitmq:
    image: rabbitmq 
    restart: always 

  app: 
    build: .
    depends_on:
    - mongodb
    - rabbitmq 
    restart: always 
  
  nginx: 
    image: nginx
    ports: 
     - "80:80"
    depends_on:
     - app 
    restart: always 
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro